name: CI
on:
  pull_request:
  push:
    branches: ['**']
    tags-ignore: ['**']

concurrency:
  group: ${{ github.event_name != 'pull_request' && github.run_id || github.ref }}
  cancel-in-progress: true

env:
  LC_ALL: 'C.UTF-8'
  LANG: 'C.UTF-8'
  LANGUAGE: 'C.UTF-8'

jobs:
  #wine-builder:
  #  name: Wine builder
  #  runs-on: ubuntu-latest
  #
  #  steps:
  #    - uses: actions/checkout@v4
  #
  #    - uses: docker/build-push-action@v5
  #      with:
  #        context: .
  #        file: contrib/build-wine.Dockerfile
  #        tags: build-wine-container
  #        load: true
  #
  #    - run: >
  #        docker run --rm \
  #          --volume ${{ github.workspace }}:${{ github.workspace }} \
  #          --workdir ${{ github.workspace }} \
  #          build-wine-container bash -c "
  #            git config --global --add safe.directory ${{ github.workspace }}
  #            contrib/build_wine.sh
  #            find dist -type f -exec sha256sum {} \;
  #          "
  #    - uses: actions/upload-artifact@v4
  #      with:
  #        name: dist-wine
  #        path: dist/
  #
  #linux-builder:
  #  name: Linux builder
  #  runs-on: ubuntu-latest
  #
  #  steps:
  #    - uses: actions/checkout@v4
  #
  #    - uses: docker/build-push-action@v5
  #      with:
  #        context: .
  #        file: contrib/build.Dockerfile
  #        tags: build-container
  #        load: true
  #
  #    - run: >
  #        docker run --rm \
  #          --volume ${{ github.workspace }}:${{ github.workspace }} \
  #          --workdir ${{ github.workspace }} \
  #          build-container bash -c "
  #            git config --global --add safe.directory ${{ github.workspace }}
  #            contrib/build_bin.sh --without-gui
  #            find dist -type f -exec sha256sum {} \;
  #          "
  #
  #    - uses: actions/upload-artifact@v4
  #      with:
  #        name: dist-linux
  #        path: dist/

  mac-builder:
    name: Mac builder
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v4

      - run: |
          brew install pyenv
          export PYENV_ROOT="$HOME/.pyenv"
          export PATH="$PYENV_ROOT/bin:$PATH"
          eval "$(pyenv init --path)"
          pyenv install 3.9
          pyenv global 3.9
          python --version
          ./contrib/build_bin.sh --without-gui

      - uses: actions/upload-artifact@v4
        with:
          name: dist-mac
          path: dist/
